### ISSUE TITLE
typo in second paragraph

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/why-layers-of-abstraction#6]
The 'if' is capitalized as if you were going to start a new sentence, but it is preceded by a comma instead of a period.

Eventually, the magic will break. In other words, your programs will **break, If you c**an't take Rails apart and understand the fundamentals of what's going on, you'll never be able to fix the magic.

**Comment by gj** [comment]
Fixed in #4. Thanks @ode-to-the-code !
